overlays:
  incomplete:
    overlay:
      name: incomplete
      group: availability
      weight: 210
    plex_search:
      any:
        label.regex: '(?i)\b(Incomplete)\b'
        
  complete:
    overlay:
      name: complete
      group: availability
      weight: 200
    plex_search:
      any:
        label.regex: '(?i)\b(Complete)\b'
        
  inprogress:
    overlay:
      name: inprogress
      group: availability
      weight: 220
    plex_search:
      any:
        label.regex: '(?i)\b(InProgress)\b'      
