templates:
  availability_template:
    <<label>:
    overlay:
      name: <<label>>_thick
      group: availability
      weight: <<weight>>
    plex_search:
      any:
        label.regex: '(?i)\b(<<label>>)\b'
  season_availability_template:
    <<label>:
    builder_level: season
    overlay_level: season
    overlay:
      name: <<label>>_thick
      group: availability
      weight: <<weight>>
    plex_search:
      any:
        label.regex: '(?i)\b(<<label>>)\b'

overlays:
  incomplete:
    template: { name: availability_template, label: Incomplete, weight: 210}
        
  complete:
    template: { name: availability_template, label: Complete, weight: 200}
        
  inprogress:
    template: { name: availability_template, label: InProgress, weight: 220}   

  incomplete_season:
    template: { name: season_availability_template, label: Incomplete, weight: 210} 
    
  complete_season:
    template: { name: season_availability_template, label: Complete, weight: 200} 
    
  inprogress_season:
    template: { name: season_availability_template, label: InProgress, weight: 220}    