overlays:
  season_incomplete:
    builder_level: season
    overlay_level: season
    overlay:
      name: incomplete
      group: season_availability
      weight: 210
    plex_search:
      any:
        season_label.regex: '(?i)\b(incomplete)\b'
        
  season_complete:
    builder_level: season
    overlay_level: season
    overlay:
      name: complete
      group: season_availability
      weight: 200
    plex_search:
      any:
        season_label.regex: '(?i)\b(complete)\b'
        
  season_inprogress:
    builder_level: season
    overlay_level: season
    overlay:
      name: inprogress
      group: season_availability
      weight: 220
    plex_search:
      any:
        season_label.regex: '(?i)\b(inprogress)\b'       
